from typing import Protocol
import torch

class EDMOPythonPlugin(Protocol):
    def __init__(self, edmoPlugin):
        self.edmoPlugin = edmoPlugin
        x = torch.rand(5, 3)
        print(x)

    def getName(self) -> str: return "EDMOPlugin2"

    def sessionStarted(self): ...
    
    def sessionEnded(self): ...

    def userJoined(self, index: int, userName: str): ...

    def userLeft(self, index: int, userName: str): ...

    def imuDataReceived(self, imuData): ...

    def oscDataReceived(self, oscillatorData): ...

    def frequencyChanged(self, index: int, freq: float): ...

    def amplitudeChanged(self, index: int, amp: float): ...

    def offsetChanged(self, index: int, off: float): ...

    def phaseShiftChanged(self, index: int, phs: float): ...
